import "./globals.css";
import { TitleProvider } from "@/context/PageTitle";
import LayoutClient from "@/components/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TitleProvider>
          <LayoutClient>{children}</LayoutClient>
        </TitleProvider>
      </body>
    </html>
  );
}
